LIFE = 3

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
MEDIUM_GRAY = (128, 128, 128)
AQUA = (0, 128, 128)
NAVY_BLUE = (0,	0, 128)
GREEN = (0, 255, 0)
ORANGE = (255, 165,	0)
YELLOW = (255, 255, 0)
RED = (255, 0, 0)

START_TEXT_SIZE = 16

REFRESH_RATE = 60



SOUND_GAME = 'media/music.wav'
SOUND_SHOT = 'media/sound_shot_1.wav' # sound_shot_1.wav

FONT = 'freesansbold.ttf'

GAME_RECORD_PATH = 'highlight.txt'

SCORE_INVADER = 100
SCORE_SHOT = 1000
SCORE_JOKER = 400
SCORE_SHOT_SHIP = 1

IMG_SHIP = 'media/ship.bmp'
IMG_INVADER_GREEN = 'media/elian_green.png'
IMG_INVADER_RED = 'media/elian_red.png'
IMG_SHOT = 'media/shot.jpeg'
IMG_JOKER = 'media/joker.PNG'
IMG_LIFE = 'media/ship.bmp'

SPEED_MOVE_SHIP = 7
SPEED_MOVE_INVADERS = 5
SPEED_DOWN_INVADERS = 15
SPEED_SHOT_SHIP = 20
PULSE_SHOTS_INVADERS = 70
PULSE_CREATE_JOKER = 300

MAX_LEVEL_ADD = 7
MIN_PROTECTORS = 3


WIDTH_SHIP, HEIGHT_SHIP = 57, 99
WIDTH_INVADER, HEIGHT_INVADER = 113, 57
WIDTH_SHOT, HEIGHT_SHOT = 5, 26

WIDTH, HEIGHT = 1600, 1158
#WIDTH_PROTECTOR =
IMG_GAME = 'media/img_game_mef.jpg'
IMG_GAME_OVER = 'media/img_over_mef.jpg'
IMG_YOU_WINNER = 'media/img_win_mef.png'
ROWS_INVADERS = 4
COLS_INVADERS = 10
LOCATION_TEXT_GAME_Y = 0.6
LOCATION_TEXT_GAME_X = 0.23


SIZE = (WIDTH, HEIGHT)
LOCATION_Y_SHIP = int(HEIGHT * 0.8)
